

CONFIGURATION_URL = 'http://configuration'
EXECUTIONS_URL = 'http://executions'

CONFIGURATION_FILE = '/root/wps/pywps.cfg'

BROKER_HOST = 'broker'
BROKER_PROTOCOL = 'amqp'
BROKER_USERNAME = 'guest'
BROKER_APPLICATION_NAME = 'lycheepy'
BROKER_PROCESS_EXECUTION_TASK_NAME = 'run_process'
BROKER_CHAIN_PROCESS_EXECUTION_TASK_NAME = 'run_chain_process'

PROCESS_EXECUTION_TIMEOUT = 30
