

CONFIGURATION_URL = 'http://configuration'
CONFIGURATION_EXECUTABLES_PATH = 'executables'
CONFIGURATION_REPOSITORIES_PATH = 'repositories'

EXECUTIONS_URL = 'http://executions'

COLLECTION_RESULTS_KEY = 'results'

CONFIGURATION_FILE = '/root/wps/pywps.cfg'

BROKER_HOST = 'broker'
BROKER_PORT = 5672
BROKER_PROTOCOL = 'amqp'
BROKER_USERNAME = 'guest'
BROKER_PASSWORD = 'guest'
BROKER_APPLICATION_NAME = 'lycheepy'
BROKER_PROCESS_EXECUTION_TASK_NAME = 'run_process'
BROKER_CHAIN_PROCESS_EXECUTION_TASK_NAME = 'run_chain_process'

PROCESS_EXECUTION_TIMEOUT = 120
