git:
  submodules: true
branches:
  only:
  - master
  - development
  - ci
before_install:
  - cd lycheepy
  - sudo bash install_host_dependencies.sh
  - cd -
install:
  - cd lycheepy
  - sudo docker-compose build
  - sudo docker-compose up -d
  - cd -
  - sleep 30
script:
  - cd tests
  - bash run.sh
