

CONFIGURATION_FILE = '/root/worker/pywps.cfg'

BROKER_HOST = 'broker'
BROKER_PORT = 5672
BROKER_PROTOCOL = 'amqp'
BROKER_USERNAME = 'guest'
BROKER_PASSWORD = 'guest'
BROKER_APPLICATION_NAME = 'lycheepy'
BROKER_PROCESS_EXECUTION_TASK_NAME = 'run_process'
BROKER_CHAIN_PROCESS_EXECUTION_TASK_NAME = 'run_chain_process'

PROCESSES_GATEWAY_HOST = 'processes'
PROCESSES_GATEWAY_USER = 'lycheepy'
PROCESSES_GATEWAY_PASS = 'lycheepy'
PROCESSES_GATEWAY_TIMEOUT = 30
PROCESSES_GATEWAY_DIRECTORY = 'processes'

LOCAL_PROCESSES_REPOSITORY = '/root/worker/processes'
