DATABASE = 'postgresql://lycheepy:lycheepy@persistence/lycheepy'
HOST = '0.0.0.0'
PORT = 5000
DEBUG = True

DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

ALLOWED_PROCESSES_EXTENSIONS = ['py']
PROCESSES_TEMPORAL_DIRECTORY = '/tmp'

PROCESSES_GATEWAY_HOST = 'processes'
PROCESSES_GATEWAY_USER = 'lycheepy'
PROCESSES_GATEWAY_PASS = 'lycheepy'
PROCESSES_GATEWAY_TIMEOUT = 5
PROCESSES_GATEWAY_DIRECTORY = ''

INDEX_GATEWAY_HOST = 'index'
INDEX_GATEWAY_PORT = 6379
INDEX_GATEWAY_DB = 0
