version: '2'
services:
    # Geospatial repository
    # Exposes OGC services and a configuration API through the 8080 port
    repository:
        build: repository
        expose:
        - "8080"
    # Exposes the WPS interface
    # Publishes on the Broker
    wps:
        build: ../install/compose/wps
        expose:
        - "80"
    # Exposes a configuration API
    configuration:
        build: ../install/compose/configuration
        expose:
        - "80"

    # Reverse proxy to the Repository, WPS, and Configuration
    proxy:
        build: proxy
        ports:
        - "80:80"

    # Persists the Configuration
    persistence:
        build: persistence
        expose:
        - "5432"

    # Receives tasks from the WPS, which are consumed by the Workers
    broker:
        build: broker
        expose:
        - "5672"

    # Consumes from the broker
    worker:
        build: worker
