version: '3'
services:
  persistence:
    build: persistence
    expose:
      - "5432"
    environment:
      POSTGRES_USER: lycheepy
      POSTGRES_PASS: lycheepy
      POSTGRES_DBNAME: lycheepy
#    ports:
#      - "5432:5432"
  configuration:
    build: configuration
    expose:
      - "80"
    depends_on:
      - persistence
      - processes
  broker:
    build: broker
    expose:
      - "5672"
  wps:
    build: wps
    expose:
      - "80"
    depends_on:
      - configuration
  repository:
    build: repository
    expose:
      - "8080"
  proxy:
    build: proxy
    ports:
      - "80:80"
    depends_on:
      - configuration
      - wps
      - repository
  worker:
    build: worker
    depends_on:
      - broker
      - processes
  processes:
    build: processes
    expose:
      - "20"
      - "21"
    environment:
      FTP_USER: lycheepy
      FTP_PASS: lycheepy
#    ports:
#      - "20:20"
#      - "21:21"
  index:
    build: index
    expose:
      - "6379"
